### PR TITLE
Update dependencies to routerify v3

### PR DESCRIPTION
**Pull request by aeyoll**
Hello,
This PR makes routerify-cors work with routerify v3. I also updated the "develop" branch, which was out of sync from master. Thanks a lot.

### CODE REVIEW

**Comment by aeyoll** [comment]
Hello @rousan, can you check the PR please? Thanks a lot.

**Comment by rousan** [comment]
Hi @aeyoll , I checked it, everything is good. But the `README.md` file needs some changes. I commented in the PR.

**Comment by aeyoll** [comment]
> Hi @aeyoll , I checked it, everything is good. But the `README.md` file needs some changes. I commented in the PR.

Hello @rousan, I don't see any other comment? I already updated the `README.md` file with the correct versions, what's missing?

**Comment by rousan** [comment]
Hi @aeyoll , Released [v3.0.0](https://github.com/routerify/routerify-cors/releases/tag/v3.0.0).

**Comment by aeyoll** [comment]
Thanks a lot @rousan  :)

**Pull request merged**
