### PR TITLE
Update to Hyper 0.14 and Tokio 1

### PR DESCRIPTION
**Pull request by seanpianka**
Keeping in line with dep updates, removed broken example since I can't fix stream_body

### CODE REVIEW

**Comment by rousan** [comment]
Please, send PR to develop branch.

**Comment by rousan** [comment]
Need to update the PR as we released the new version of Routerify.

**Comment by ta3pks** [comment]
I was gonna do this by myself lucky i saw your pr first. @rousan  approximately when do you think we will have a 2.0 release so this can be merged ?

**Comment by seanpianka** [comment]
@NikosEfthias An updated version of these drop-in middlewares are to be released when a new major version release of Routerify is made.

Please continue the discussion [here](https://github.com/routerify/routerify/issues/53).

**Comment by ta3pks** [comment]
@seanpianka have you tested this against v2 ?

**Comment by seanpianka** [comment]
The Cargo.toml needs to be updated to use v2, @NikosEfthias. Once that change is merged to master, we should then create a new release on crates.io.

**Review by ta3pks — APPROVED** [review]

**Pull request closed without merging**
