### PR TITLE
Draft: Requestservicebuilder

### PR DESCRIPTION
**Pull request by seanpianka**

### CODE REVIEW

**Comment by ta3pks** [comment]
@seanpianka this seems to be identical to your other pr. Unless theres something I am missing i thing we should close this one

**Comment by seanpianka** [comment]
@NikosEfthias These repositories must be updated to the newest release.

This will be done after a major release. Feel free to fork and create your own, using a recent beta release.

**Comment by seanpianka** [comment]
And yes, do not merge this PR. I will mark it as a draft, as it's intended to test RequestServiceBuilder on the v1 Routerify API.

**Review by ta3pks — APPROVED** [review]

**Comment by ta3pks** [comment]
can you create a pr to develop branch please @seanpianka

**Pull request merged**
